" Generated by vim-plug
" Fri 18 Sep 2020 13:55:45
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['coc.nvim'].commit = '825f7f5b89fb1708f18711798ef7a2ba6aa1bde5'
silent! let g:plugs['ctrlp.vim'].commit = '564176f01d7f3f7f8ab452ff4e1f5314de7b0981'
silent! let g:plugs['ctrlp_bdelete.vim'].commit = 'c3a855d3cccb629298ed6a5fbd670f87ec7061ef'
silent! let g:plugs['gist-vim'].commit = '2158eceb210b0a354bc17aa4144554e5d8bb6c79'
silent! let g:plugs['idris-vim'].commit = '091ed6b267749927777423160eeab520109dd9c1'
silent! let g:plugs['julia-vim'].commit = '33116e1135ffa0c09997c111785beb5232efc7cf'
silent! let g:plugs['rust.vim'].commit = '2a6736852cbe64e2883adc70a427cb47cb3305bc'
silent! let g:plugs['terminus'].commit = '340ea44dfec58c9d48e46c97c90896ed04e2a264'
silent! let g:plugs['vim-abolish'].commit = '7e4da6e78002344d499af9b6d8d5d6fcd7c92125'
silent! let g:plugs['vim-airline'].commit = '3740312de0be5200286260816e2563e77c0be0c5'
silent! let g:plugs['vim-commentary'].commit = 'f8238d70f873969fb41bf6a6b07ca63a4c0b82b1'
silent! let g:plugs['vim-easy-align'].commit = '12dd6316974f71ce333e360c0260b4e1f81169c3'
silent! let g:plugs['vim-endwise'].commit = '97180a73ad26e1dcc1eebe8de201f7189eb08344'
silent! let g:plugs['vim-eunuch'].commit = '4a4bf16b499dcde371c05c77ed4083c4b5228278'
silent! let g:plugs['vim-fish'].commit = '50b95cbbcd09c046121367d49039710e9dc9c15f'
silent! let g:plugs['vim-fugitive'].commit = '511d3035d4da2453a9cb0188b6020ed7bc8fc18f'
silent! let g:plugs['vim-lean'].commit = '02d678e4346dce35d6b2eed9a03b2b2d3cc84127'
silent! let g:plugs['vim-nix'].commit = 'd733cb96707a2a6bdc6102b6d89f947688e0e959'
silent! let g:plugs['vim-pasta'].commit = 'cb4501a123d74fc7d66ac9f10b80c9d393746c66'
silent! let g:plugs['vim-racket'].commit = 'bca2643c3d8bd0fcd46ab73bee69023a5da1964b'
silent! let g:plugs['vim-repeat'].commit = 'c947ad2b6a16983724a0153bdf7f66d7a80a32ca'
silent! let g:plugs['vim-rhubarb'].commit = '5130596a65330a4e8523d3ac1582f6c31ea6bc63'
silent! let g:plugs['vim-sleuth'].commit = 'ea3f065f23cd0592062b8226c8fef08b6af3b459'
silent! let g:plugs['vim-surround'].commit = 'f51a26d3710629d031806305b6c8727189cd1935'
silent! let g:plugs['vim-textobj-comment'].commit = '58ae4571b76a5bf74850698f23d235eef991dd4b'
silent! let g:plugs['vim-textobj-parameter'].commit = '201144f19a1a7081033b3cf2b088916dd0bcb98c'
silent! let g:plugs['vim-textobj-user'].commit = '41a675ddbeefd6a93664a4dc52f302fe3086a933'
silent! let g:plugs['vim-toml'].commit = '897cb4eaa81a0366bc859effe14116660d4015cd'
silent! let g:plugs['vim-vinegar'].commit = '5fee9d230ec4a6a16c45f2c71482595e4d9a67bd'
silent! let g:plugs['webapi-vim'].commit = '10b8e926d85a3ab689c2966a3df1139bcb4e197f'

PlugUpdate!

