" Generated by vim-plug
" Wed 07 Apr 2021 19:31:22
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['coc.nvim'].commit = 'd3e40ceabd76323c07434fc2711521cc8bb2d028'
silent! let g:plugs['fzf'].commit = 'fefdb8c84ec41ace6b87784e78ed98ca6d0a1e7d'
silent! let g:plugs['fzf.vim'].commit = 'caf7754b2636eabdf1bc11d30daccc5de66951ef'
silent! let g:plugs['idris-vim'].commit = '091ed6b267749927777423160eeab520109dd9c1'
silent! let g:plugs['julia-vim'].commit = '21ab5e899db6ad963b30102e14fb13be8eeb454c'
silent! let g:plugs['rust.vim'].commit = '87c745d8d506fc1eecc1d81df15d5bde1658a2fc'
silent! let g:plugs['terminus'].commit = '51c9bf43427af5ddff7352707a2bdab58cac9593'
silent! let g:plugs['vim-abolish'].commit = '3f0c8faadf0c5b68bcf40785c1c42e3731bfa522'
silent! let g:plugs['vim-airline'].commit = 'ed60e1d36912f64fdbed5640532b1067e11557ca'
silent! let g:plugs['vim-characterize'].commit = 'af156501e8a8855832f15c2cc3d6cefb2d7f7f52'
silent! let g:plugs['vim-commentary'].commit = '349340debb34f6302931f0eb7139b2c11dfdf427'
silent! let g:plugs['vim-easy-align'].commit = '12dd6316974f71ce333e360c0260b4e1f81169c3'
silent! let g:plugs['vim-endwise'].commit = '4289889a2622f9bc7c594a6dd79763781f63dfb5'
silent! let g:plugs['vim-eunuch'].commit = 'dbbbf853fc523d312f61b4bbdf2e13297645dcde'
silent! let g:plugs['vim-fish'].commit = '50b95cbbcd09c046121367d49039710e9dc9c15f'
silent! let g:plugs['vim-fugitive'].commit = '8ede0aaf57e1dbb5416ddbe30d0bfdde762e90bf'
silent! let g:plugs['vim-gist'].commit = '4a210316550577c1b6a5cb13b09ce79fba602b9c'
silent! let g:plugs['vim-gomod'].commit = 'd6e736037290f08cf99296cb0407f22456022f48'
silent! let g:plugs['vim-lean'].commit = '02d678e4346dce35d6b2eed9a03b2b2d3cc84127'
silent! let g:plugs['vim-nix'].commit = '7542a2bf66d72cb86fc80529867accbc787f744b'
silent! let g:plugs['vim-pasta'].commit = 'cb4501a123d74fc7d66ac9f10b80c9d393746c66'
silent! let g:plugs['vim-racket'].commit = 'bca2643c3d8bd0fcd46ab73bee69023a5da1964b'
silent! let g:plugs['vim-repeat'].commit = '24afe922e6a05891756ecf331f39a1f6743d3d5a'
silent! let g:plugs['vim-rhubarb'].commit = '1c36bf8668e329b51f8baf752c4ffe42f8d524ab'
silent! let g:plugs['vim-sleuth'].commit = '38bd4010110614822cde523ebc5724963312ab63'
silent! let g:plugs['vim-surround'].commit = 'f51a26d3710629d031806305b6c8727189cd1935'
silent! let g:plugs['vim-textobj-comment'].commit = '58ae4571b76a5bf74850698f23d235eef991dd4b'
silent! let g:plugs['vim-textobj-parameter'].commit = '201144f19a1a7081033b3cf2b088916dd0bcb98c'
silent! let g:plugs['vim-textobj-user'].commit = '41a675ddbeefd6a93664a4dc52f302fe3086a933'
silent! let g:plugs['vim-toml'].commit = '3c5face8e8944a217af45bc5bb708ff7dfcf1a54'
silent! let g:plugs['vim-vinegar'].commit = 'b245f3ab4580eba27616a5ce06a56d5f791e67bd'
silent! let g:plugs['vim-xquery-syntax'].commit = '7013f63f0e5e052634d760efd3eaa9e4802af9b7'
silent! let g:plugs['webapi-vim'].commit = '6f5ffb6f547cda1b6cbc26a06f12d81e6283bd82'

PlugUpdate!

