#!/usr/bin/env bash

# FIXME: Remove this Nix-specific bit.
if command -v nix-shell >/dev/null 2>&1; then
  ansifilter='nix-shell -p ansifilter --run ansifilter'
else
  ansifilter=ansifilter
fi

exec vim -MRn \
  -c 'set ft=man nonumber nolist colorcolumn=' \
  -c 'map q :q<CR>' \
  < /dev/tty \
  <($ansifilter)
