#!/usr/bin/env bash

if command -v ansifilter >/dev/null 2>&1; then
  ansifilter=ansifilter
elif command -v nix-shell >/dev/null 2>&1; then
  ansifilter='nix-shell -p ansifilter --run ansifilter'
else
  ansifilter='col -bx'
fi

exec vim -MRn \
  -c 'set ft=man nonumber nolist colorcolumn=' \
  -c 'map q :q<CR>' \
  < /dev/tty \
  <($ansifilter)
