#!/usr/bin/env ruby

require 'shellwords'

start_time = Time.now
title = system(*ARGV) ? 'Success' : 'Failure'
end_time = Time.now

seconds = end_time - start_time

if seconds > 5
  millis = (seconds * 1000).to_i
  elapsed = `format-duration #{millis}`
  title += " after #{elapsed}"

  system('push-notify', title, ARGV.join(' '))
end
